# This is a basic workflow to help you get started with Actions

name: DeployToNas

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: another scp
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          # ssh remote host
          host: ${{ secrets.NAS_HOST }}
          # ssh remote port
          port: ${{ secrets.NAS_PORT }} # optional, default is 22
          # ssh remote user
          user: ${{ secrets.NAS_USER }}
          # ssh remote password
          pass: ${{ secrets.NAS_PASSWORD }} # optional
          connect_timeout: 10s
          scp: |
            ./src/ => /volume1/docker/phonetic-symbol/html/
